version: '3.8'
services:
  nps:
    image: aiastia/nps:latest
    container_name: ${CONTAINER_NAME}
    hostname: nps-server
    restart: unless-stopped
    network_mode: host  # 必须使用host模式
    volumes:
      - ./conf:/conf                  # 配置文件目录
      - ${WEB_KEY_FILE}:/conf/server.key  # SSL证书私钥
      - ${WEB_CERT_FILE}:/conf/server.pem  # SSL证书
    environment:
      # 核心参数 (对应config.yml表单字段)
      - RUN_MODE=${RUN_MODE:-dev}
      - HTTP_PROXY_PORT=${PANEL_APP_PORT_HTTP_PROXY_PORT:-8880}
      - HTTPS_PROXY_PORT=${PANEL_APP_PORT_HTTPS_PROXY_PORT:-4443}
      - BRIDGE_PORT=${PANEL_APP_PORT_BRIDGE_PORT:-8024}
      - WEB_PORT=${PANEL_APP_PORT_WEB_PORT:-8080}
      - PUBLIC_VKEY=${PUBLIC_VKEY}
      - WEB_USERNAME=${WEB_USERNAME:-admin}
      - WEB_PASSWORD=${WEB_PASSWORD}
      - WEB_HOST=${WEB_HOST}
      - ALLOW_PORTS=${ALLOW_PORTS:-9001-9009,10001,11000-12000}
      - AUTH_KEY=${AUTH_KEY}
      - AUTH_CRYPT_KEY=${AUTH_CRYPT_KEY}
      
      # SSL配置
      - WEB_OPEN_SSL=${WEB_OPEN_SSL:-false}
      - WEB_CERT_FILE=${WEB_CERT_FILE:-conf/server.pem}
      - WEB_KEY_FILE=${WEB_KEY_FILE:-conf/server.key}
      
      # 高级配置
      - WEB_IP=${WEB_IP:-0.0.0.0}
      - WEB_BASE_URL=${WEB_BASE_URL:-}
      - BRIDGE_TYPE=${BRIDGE_TYPE:-tcp}
      - BRIDGE_IP=${BRIDGE_IP:-0.0.0.0}
      - FLOW_STORE_INTERVAL=${FLOW_STORE_INTERVAL:-1}
      - LOG_LEVEL=${LOG_LEVEL:-7}
      - ALLOW_USER_LOGIN=${ALLOW_USER_LOGIN:-true}
      - ALLOW_USER_REGISTER=${ALLOW_USER_REGISTER:-false}
      - ALLOW_USER_CHANGE_USERNAME=${ALLOW_USER_CHANGE_USERNAME:-false}
      - ALLOW_FLOW_LIMIT=${ALLOW_FLOW_LIMIT:-true}
      - ALLOW_RATE_LIMIT=${ALLOW_RATE_LIMIT:-true}
      - ALLOW_TUNNEL_NUM_LIMIT=${ALLOW_TUNNEL_NUM_LIMIT:-true}
      - ALLOW_LOCAL_PROXY=${ALLOW_LOCAL_PROXY:-true}
      - ALLOW_CONNECTION_NUM_LIMIT=${ALLOW_CONNECTION_NUM_LIMIT:-true}
      - ALLOW_MULTI_IP=${ALLOW_MULTI_IP:-false}
      - SYSTEM_INFO_DISPLAY=${SYSTEM_INFO_DISPLAY:-true}
      - HTTP_CACHE=${HTTP_CACHE:-true}
      - HTTP_CACHE_LENGTH=${HTTP_CACHE_LENGTH:-100}
      
      # NPC客户端配置
      - NPC_SERVER_ADDR=${NPC_SERVER_ADDR:-127.0.0.1}
      - NPC_CONN_TYPE=${NPC_CONN_TYPE:-tcp}
      - NPC_AUTO_RECONNECTION=${NPC_AUTO_RECONNECTION:-true}
      - NPC_CRYPT=${NPC_CRYPT:-true}
      - NPC_COMPRESS=${NPC_COMPRESS:-true}
      - NPC_REMARK=${NPC_REMARK:-nps}
      - NPC_WEB_ADMIN_MODE=${NPC_WEB_ADMIN_MODE:-https}
      - NPC_WEB_FILE_MODE=${NPC_WEB_FILE_MODE:-http}
      - NPC_FILE_MODE=${NPC_FILE_MODE:-file}
      - NPC_FILE_SERVER_PORT=${NPC_FILE_SERVER_PORT:-8081}
      - NPC_FILE_LOCAL_PATH=${NPC_FILE_LOCAL_PATH:-/file/}
      - NPC_FILE_STRIP_PRE=${NPC_FILE_STRIP_PRE:-/}
      
      # 时区设置
      - TZ=${TZ:-Asia/Shanghai}
