version: '3.8'
services:
  nps:
    image: aiastia/npc:dev
    container_name: ${CONTAINER_NAME}
    hostname: nps-server
    restart: unless-stopped
    network_mode: host  # 必须使用host模式
    volumes:
      - ./conf:/conf                  # 配置文件目录
      - ${WEB_KEY_FILE}:/conf/server.key  # SSL证书私钥
      - ${WEB_CERT_FILE}:/conf/server.pem  # SSL证书
    environment:
      # 核心参数 (对应config.yml表单字段)
      - RUN_MODE=${RUN_MODE:-dev}
      - HTTP_PROXY_PORT=${PANEL_APP_PORT_HTTP_PROXY_PORT:-8880}
      - HTTPS_PROXY_PORT=${PANEL_APP_PORT_HTTPS_PROXY_PORT:-4443}
      - BRIDGE_PORT=${PANEL_APP_PORT_BRIDGE_PORT:-8024}
      - WEB_PORT=${PANEL_APP_PORT_WEB_PORT:-8080}
      - PUBLIC_VKEY=${PUBLIC_VKEY}
      - WEB_USERNAME=${WEB_USERNAME:-admin}
      - WEB_PASSWORD=${WEB_PASSWORD}
      - WEB_HOST=${WEB_HOST}
      - ALLOW_PORTS=${ALLOW_PORTS:-9001-9009,10001,11000-12000}
      - AUTH_KEY=${AUTH_KEY}
      - AUTH_CRYPT_KEY=${AUTH_CRYPT_KEY}

      # 固定参数 (保持与nps.conf一致)
      - BRIDGE_TYPE=tcp
      - BRIDGE_IP=0.0.0.0
      - FLOW_STORE_INTERVAL=1
      - AUTH_KEY=123654789
      - AUTH_CRYPT_KEY=12340567812345678
